---
name: "Media Cleaner"
guid: "607fee77-97eb-41fe-bf22-26844d99ffb0"
version: "1.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
overview: "Delete played media after specified time"
description: >
  Keep your storage clean without hassle.
  Works with movies and series.
category: "General"
owner: "shemanaev"
artifacts:
- "MediaCleaner.dll"
changelog: >
  Initial version.
