---
name: "Media Cleaner"
guid: "607fee77-97eb-41fe-bf22-26844d99ffb0"
version: "2.6.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Delete played media after specified time"
description: >
  Keep your storage clean without hassle.
  Works with movies and series.
category: "General"
owner: "shemanaev"
artifacts:
- "MediaCleaner.dll"
changelog: >
  Add "mark as unplayed"
  Add html rendered log view
